version: 2

project_name: sandman

before:
  hooks:
    - go mod tidy

builds:
  - id: sandman-binary
    binary: sandman
    env: [CGO_ENABLED=0]
    goos: [linux, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X sandman/cmd.Version={{.Version}}

nfpms:
  - file_name_template: "sandman_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [deb, rpm]
    vendor: "th3-v3ng34nc3"
    homepage: "https://github.com/th3-v3ng34nc3/sandman"
    maintainer: "th3-v3ng34nc3 <https://github.com/th3-v3ng34nc3>"
    description: "Unified security scanner wrapping Trivy, Opengrep, and OWASP ZAP"

archives:
  - formats: [zip]
    name_template: "sandman_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
